ALERT_TYPE_THRESOLD = 0
ALERT_TYPE_DEADMAN = 1
CHOICE_ALERT_TYPE = (
    (ALERT_TYPE_THRESOLD, "thresold"),
    (ALERT_TYPE_DEADMAN, "deadman"),
)

ALARM_TYPE_SINGLE = 0
ALARM_TYPE_MULTI = 1
CHOICE_ALARM_TYPE = (
    (ALARM_TYPE_SINGLE, "single alarm"),
    (ALARM_TYPE_MULTI, "multi alarm"),
)