# Generated by Django 4.1.5 on 2023-02-01 04:55

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('mac_address', models.CharField(db_index=True, max_length=20)),
                ('measurement', models.CharField(blank=True, max_length=255, null=True)),
                ('bucket', models.CharField(blank=True, max_length=255, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('deadman', models.IntegerField(default=3600)),
                ('period', models.IntegerField(default=60)),
                ('brand', models.CharField(blank=True, max_length=64, null=True)),
                ('output_parameters', models.JSONField(default=dict)),
                ('control_parameters', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AlertSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('condition', models.JSONField(default=list)),
                ('action', models.JSONField(default=list)),
                ('enable', models.BooleanField(default=False)),
                ('alarm', models.BooleanField(default=True)),
                ('last_alert', models.DateTimeField(default=None, null=True)),
                ('period', models.IntegerField(default=60)),
                ('delay_time', models.IntegerField(default=0)),
                ('snooze_time', models.IntegerField(default=0)),
                ('alert_type', models.IntegerField(choices=[(0, 'thresold'), (1, 'deadman')], default=0)),
                ('alarm_type', models.IntegerField(choices=[(0, 'single alarm'), (1, 'multi alarm')], default=0)),
                ('last_view', models.DateTimeField(default=None, null=True)),
                ('devices', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alert_setting_devices', to='scheduler.device')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('original_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
